# Generated by Django 5.2.8 on 2025-12-06 09:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Quiz",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("content", models.CharField(max_length=255)),
                ("slug", models.CharField(max_length=255, unique=True)),
            ],
            options={
                "db_table": "quiz",
            },
        ),
        migrations.CreateModel(
            name="Question",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("quiz", models.ForeignKey(on_delete=models.CASCADE, to="quiz.Quiz")),
                ("content", models.TextField()),
                ("position", models.IntegerField(blank=True, null=True)),
            ],
            options={
                "db_table": "question",
                "ordering": ["position"],
            },
        ),
        migrations.CreateModel(
            name="Answers",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("question", models.ForeignKey(on_delete=models.CASCADE, to="quiz.Question")),
                ("content", models.TextField()),
                ("is_correct", models.BooleanField(default=False)),
            ],
            options={
                "db_table": "answers",
            },
        ),
        migrations.CreateModel(
            name="Users",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("username", models.CharField(max_length=100, unique=True)),
                ("password", models.CharField(max_length=255)),
                ("role", models.CharField(max_length=50)),
                ("mail", models.CharField(max_length=255, unique=True)),
            ],
            options={
                "db_table": "users",
            },
        ),
        migrations.CreateModel(
            name="QuizAttempt",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("quiz", models.ForeignKey(on_delete=models.CASCADE, to="quiz.Quiz")),
                ("user", models.ForeignKey(on_delete=models.CASCADE, to="quiz.Users")),
                ("start_date", models.DateTimeField(blank=True, null=True)),
                ("end_date", models.DateTimeField(blank=True, null=True)),
                ("correct", models.IntegerField(blank=True, null=True)),
                ("incorrect", models.IntegerField(blank=True, null=True)),
            ],
            options={
                "db_table": "quiz_attempt",
            },
        ),
        migrations.CreateModel(
            name="QuizSession",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("quiz", models.ForeignKey(on_delete=models.CASCADE, to="quiz.Quiz")),
                ("host", models.ForeignKey(on_delete=models.CASCADE, to="quiz.Users")),
                ("access_code", models.CharField(max_length=20)),
                ("start_time", models.DateTimeField(blank=True, null=True)),
                ("end_time", models.DateTimeField(blank=True, null=True)),
                ("is_active", models.BooleanField(blank=True, null=True)),
            ],
            options={
                "db_table": "quiz_session",
            },
        ),
        migrations.CreateModel(
            name="QuizUser",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("quiz", models.ForeignKey(on_delete=models.CASCADE, to="quiz.Quiz")),
                ("user", models.ForeignKey(on_delete=models.CASCADE, to="quiz.Users")),
            ],
            options={
                "db_table": "quiz_user",
            },
        ),
        migrations.CreateModel(
            name="QuizStat",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("quiz", models.OneToOneField(on_delete=models.CASCADE, to="quiz.Quiz")),
                ("total_attempts", models.IntegerField(default=0)),
                ("total_correct", models.IntegerField(default=0)),
                ("total_incorrect", models.IntegerField(default=0)),
            ],
            options={
                "db_table": "quiz_stat",
            },
        ),
        migrations.CreateModel(
            name="QuestionStat",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("question", models.OneToOneField(on_delete=models.CASCADE, to="quiz.Question")),
                ("times_asked", models.IntegerField(default=0)),
                ("times_correct", models.IntegerField(default=0)),
            ],
            options={
                "db_table": "question_stat",
            },
        ),
        migrations.CreateModel(
            name="AnswerStat",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("answer", models.OneToOneField(on_delete=models.CASCADE, to="quiz.Answers")),
                ("times_selected", models.IntegerField(default=0)),
                ("times_selected_correct", models.IntegerField(default=0)),
            ],
            options={
                "db_table": "answer_stat",
            },
        ),
    ]
