# Generated by Django 5.2.8 on 2025-12-06 09:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Answers",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("content", models.TextField()),
                ("is_correct", models.IntegerField(blank=True, null=True)),
            ],
            options={
                "db_table": "answers",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="Question",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("content", models.TextField()),
                ("position", models.IntegerField(blank=True, null=True)),
            ],
            options={
                "db_table": "question",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="Quiz",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("content", models.CharField(max_length=255)),
                ("slug", models.CharField(max_length=255, unique=True)),
            ],
            options={
                "db_table": "quiz",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="QuizAttempt",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("start_date", models.DateTimeField(blank=True, null=True)),
                ("end_date", models.DateTimeField(blank=True, null=True)),
                ("correct", models.IntegerField(blank=True, null=True)),
                ("incorrect", models.IntegerField(blank=True, null=True)),
            ],
            options={
                "db_table": "quiz_attempt",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="QuizSession",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("access_code", models.CharField(max_length=20)),
                ("start_time", models.DateTimeField(blank=True, null=True)),
                ("end_time", models.DateTimeField(blank=True, null=True)),
                ("is_active", models.IntegerField(blank=True, null=True)),
            ],
            options={
                "db_table": "quiz_session",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="QuizUser",
            fields=[
                (
                    "pk",
                    models.CompositePrimaryKey(
                        "quiz_id",
                        "user_id",
                        blank=True,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
            ],
            options={
                "db_table": "quiz_user",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="Users",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("username", models.CharField(max_length=100, unique=True)),
                ("password", models.CharField(max_length=255)),
                ("role", models.CharField(max_length=50)),
                ("mail", models.CharField(max_length=255, unique=True)),
            ],
            options={
                "db_table": "users",
                "managed": False,
            },
        ),
    ]
