# Generated by Django 6.0 on 2026-01-03 16:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='answers',
            options={},
        ),
        migrations.AlterModelOptions(
            name='question',
            options={'ordering': ['position']},
        ),
        migrations.AlterModelOptions(
            name='quiz',
            options={},
        ),
        migrations.AlterModelOptions(
            name='quizattempt',
            options={},
        ),
        migrations.AlterModelOptions(
            name='quizsession',
            options={},
        ),
        migrations.AlterModelOptions(
            name='quizuser',
            options={},
        ),
        migrations.AlterModelOptions(
            name='users',
            options={},
        ),
    ]
